In [2]:
import torch
import numpy as np

### Tensors

In [23]:
print(torch.Tensor(2, 3))              # uninitialized
print(torch.rand(3))                   # uniform random
print(torch.randn(3))                  # normal random
print(torch.eye(3))                    # identity matrix NxN
print(torch.from_numpy(np.arange(3)))
print(torch.linspace(0, 3, 5))         # 5 values from 0 to 5
print(torch.arange(5))
print(torch.arange(0, 15, 5))          # values from 0 to 15 exclusive, step 5
print(torch.zeros(3))
print(torch.ones(3))
print(torch.zeros_like(torch.ones(3)))

tensor([[ 0.0000e+00, -2.5244e-29,  4.3691e-03],
        [ 2.8586e-42,  4.3640e-03,  1.0845e-19]])
tensor([0.5783, 0.2644, 0.8099])
tensor([-1.0312, -1.0083, -0.0303])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 1, 2])
tensor([0.0000, 0.7500, 1.5000, 2.2500, 3.0000])
tensor([0, 1, 2, 3, 4])
tensor([ 0,  5, 10])
tensor([0., 0., 0.])
tensor([1., 1., 1.])
tensor([0., 0., 0.])


In [26]:
print(torch.tensor(5))
print(torch.tensor([1,2]))
print(torch.tensor([[1,2],[3,4]]))
print(torch.zeros(5, dtype=torch.int32))

tensor(5)
tensor([1, 2])
tensor([[1, 2],
        [3, 4]])
tensor([0, 0, 0, 0, 0], dtype=torch.int32)


In [11]:
print(torch.zeros([5,5]).shape)
print(torch.zeros([5,5]).size())
print(torch.zeros([5,5]).numel())     # number of elements
print(torch.tensor(5).item())         # only 1 element can be converted
print(torch.tensor([1]).item())
print(torch.tensor([[1]]).item())

torch.Size([5, 5])
torch.Size([5, 5])
25
5
1
1


In [59]:
# Reshaping
x = torch.ones(2, 3)
print(x.reshape(3, 2))
print(x.reshape(3, -1))
print(x.reshape(-1, 2))
print(x.flatten())
print(x.reshape(-1))               # same as flatten
print(x.reshape(-1, 6).squeeze())
print(x.unsqueeze(dim=0))
print(x.unsqueeze(dim=1))
print(x.unsqueeze(dim=2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1.])
tensor([[[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[1., 1., 1.]],

        [[1., 1., 1.]]])
tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])


In [10]:
# torch.view returns a new tensor which is a view of the original tensor.
# It will share data with the original tensor.
# torch.reshape may create a new tensor.
x = torch.ones(2, 3)
print(x.view(3, 2))
print(x.view(-1, 2))
print(x.view(3, -1))
print(x.view(-1))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([1., 1., 1., 1., 1., 1.])


In [67]:
print(torch.cat((torch.ones(2, 2), torch.zeros(2, 2))))
print(torch.cat((torch.ones(2, 2), torch.zeros(2, 2)), dim=1))
print(torch.stack((torch.ones(2, 2), torch.zeros(2, 2))))

tensor([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.]])
tensor([[[1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.]]])


In [143]:
# Operations
print(torch.tensor([1, 2]) + torch.tensor([3, 4]))
x = torch.tensor([[1, 2], [3, 4]])
print(x.mm(x))
print(x @ x)
print(x.mul(x))
print(x * x)
print(torch.sum(x))
print(torch.cumprod(torch.arange(1, 5), dim=0))
print(torch.mean(x.double()))
print(torch.std(x.type(torch.DoubleTensor)))
x.add_(5)
print(x)

tensor([4, 6])
tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor(10)
tensor([ 1,  2,  6, 24])
tensor(2.5000, dtype=torch.float64)
tensor(1.2910, dtype=torch.float64)
tensor([[6, 7],
        [8, 9]])


In [13]:
a = torch.tensor([1, 2])
b = a.numpy() # a & b share memory
print(b)
a.add_(1) # so updating a also updates b
print(a)
print(b)

[1 2]
tensor([2, 3])
[2 3]


In [14]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())
#print(torch.zeros(3).cuda())             # PyTorch must be compiled with CUDA enabled
print(torch.zeros(3).cpu())
print(torch.zeros(3).is_cuda)
print(torch.zeros(3).device)
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print(torch.zeros(3).to(device))

False
0
tensor([0., 0., 0.])
False
cpu
tensor([0., 0., 0.])


### Autograd

In [41]:
print(torch.tensor(5).requires_grad)    # Variables are deprecated. Autograd supports Tensors

False


In [107]:
x = torch.ones(1, 5)
w = torch.rand(5, 1, requires_grad=True)
b = torch.rand(1, requires_grad=True)
y = x.mm(w) + b
print(y)
print(y.requires_grad)
y.backward()
print(w.grad)
print(b.grad)
print(x.grad)

tensor([[3.1171]], grad_fn=<AddBackward0>)
True
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])
tensor([1.])
None


### Modules

In [106]:
linear = torch.nn.Linear(5, 1)
print(linear.weight)
print(list(linear.parameters()))
print(linear(torch.ones(5)))

Parameter containing:
tensor([[-0.2835,  0.2894,  0.4138, -0.1660,  0.2369]], requires_grad=True)
[Parameter containing:
tensor([[-0.2835,  0.2894,  0.4138, -0.1660,  0.2369]], requires_grad=True), Parameter containing:
tensor([0.3747], requires_grad=True)]
tensor([0.8652], grad_fn=<AddBackward0>)


In [123]:
class MyLinearModel(torch.nn.Module):
    def __init__(self, n):
        super(MyLinearModel, self).__init__()
        self.w = torch.nn.Parameter(torch.rand(n, 1, requires_grad=True))
        self.b = torch.nn.Parameter(torch.rand(1, requires_grad=True))

    def forward(self, x):
        return x.mm(self.w) + self.b

In [133]:
my_linear = MyLinearModel(5)
y = my_linear(torch.ones(1, 5))
print(y)

tensor([[2.9110]], grad_fn=<AddBackward0>)


In [125]:
list(my_linear.parameters())

[Parameter containing:
 tensor([[0.5733],
         [0.5029],
         [0.8559],
         [0.9127],
         [0.0204]], requires_grad=True), Parameter containing:
 tensor([0.1813], requires_grad=True)]

In [110]:
import torch.nn.functional as F
F.relu(torch.tensor([-1, 1]))

tensor([0, 1])

### Losses

In [129]:
loss = torch.nn.MSELoss()
print(loss(torch.ones(5), torch.zeros(5)))

tensor(1.)


### Optimizers

In [137]:
x = torch.ones(1, 5)
w = torch.rand(5, 1, requires_grad=True)
y = x.mm(w).mean()

y.backward()
print(w.data)

opt = torch.optim.SGD([w], lr=1e-3)
opt.step()
print(w.data)

tensor([[0.7688],
        [0.6662],
        [0.0258],
        [0.9909],
        [0.6336]])
tensor([[0.7678],
        [0.6652],
        [0.0248],
        [0.9899],
        [0.6326]])


### Data Loading

In [142]:
import torch.utils.data

class MyDataset(torch.utils.data.Dataset):
  def __len__(self):
    return 23

  def __getitem__(self, index):
    return index

data_loader = torch.utils.data.DataLoader(
    MyDataset(), batch_size=4, shuffle=True, num_workers=2, drop_last=True)

for i, batch in enumerate(data_loader):
    print(i, batch)

0 tensor([ 0, 19,  6, 10])
1 tensor([13,  5,  2,  4])
2 tensor([11, 17,  1, 16])
3 tensor([22, 14,  9,  8])
4 tensor([ 3, 18, 12, 21])


Resources
* http://www.goldsborough.me/ml/ai/python/2018/02/04/20-17-20-a_promenade_of_pytorch/
* https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/
* http://deeplizard.com/learn/video/fCVuiW9AFzY