In [1]:
import numpy as np
import pandas as pd
import os

from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

In [2]:
df = pd.read_csv('/Users/anton/mywork/Datasets/Quora/train.csv')

In [3]:
df.shape

(1306122, 3)

In [4]:
df

qid  \
0        00002165364db923c7e6   
1        000032939017120e6e44   
2        0000412ca6e4628ce2cf   
3        000042bf85aa498cd78e   
4        0000455dfa3e01eae3af   
5        00004f9a462a357c33be   
6        00005059a06ee19e11ad   
7        0000559f875832745e2e   
8        00005bd3426b2d0c8305   
9        00006e6928c5df60eacb   
10       000075f67dd595c3deb5   
11       000076f3b42776c692de   
12       000089792b3fc8026741   
13       000092a90bcfbfe8cd88   
14       000095680e41a9a6f6e3   
15       0000a89942e3143e333a   
16       0000b8e1279eaa0a7062   
17       0000bc0f62500f55959f   
18       0000ce6c31f14d3e09ec   
19       0000d329332845b8a7fa   
20       0000dd973dfd35508c16   
21       0000e4d455f9c8877dc9   
22       0000e91571b60c2fb487   
23       000101ac65db6e4a1c13   
24       00010632971fe5e3e0e2   
25       00010a2e064c3e8f152a   
26       00012011b6c7759461e8   
27       00012fd5128d576260ab   
28       0001303b1799a042b26b   
29       00013a8152b5f37b780e   
...                       ...   
1306092  fffeaee9356b09078753   
1306093  fffeba722d9b371bd1b9   
1306094  fffee269360dd0d3947a   
1306095  fffee78cd374c14d15f8   
1306096  fffef2de11d291406fdb   
1306097  fffef6ecdfd410ddd5c0   
1306098  ffff0e0bad740a698663   
1306099  ffff0e4ea1bb6e16feec   
1306100  ffff265faac66b6085da   
1306101  ffff2adc1895bc0c32e1   
1306102  ffff3778790af9baae76   
1306103  ffff3f0a2449ffe4b9ff   
1306104  ffff41393389d4206066   
1306105  ffff42493fc203cd9532   
1306106  ffff48dd47bee89fff79   
1306107  ffff5fd051a032f32a39   
1306108  ffff6d528040d3888b93   
1306109  ffff8776cd30cdc8d7f8   
1306110  ffff94d427ade3716cd1   
1306111  ffffa382c58368071dc9   
1306112  ffffa5b0fa76431c063f   
1306113  ffffae5dbda3dc9e9771   
1306114  ffffba7c4888798571c1   
1306115  ffffc0c7158658a06fd9   
1306116  ffffc404da586ac5a08f   
1306117  ffffcc4e2331aaf1e41e   
1306118  ffffd431801e5a2f4861   
1306119  ffffd48fb36b63db010c   
1306120  ffffec519fa37cf60c78   
1306121  ffffed09fedb5088744a   

                                             question_text  target  
0        How did Quebec nationalists see their province...       0  
1        Do you have an adopted dog, how would you enco...       0  
2        Why does velocity affect time? Does velocity a...       0  
3        How did Otto von Guericke used the Magdeburg h...       0  
4        Can I convert montra helicon D to a mountain b...       0  
5        Is Gaza slowly becoming Auschwitz, Dachau or T...       0  
6        Why does Quora automatically ban conservative ...       0  
7        Is it crazy if I wash or wipe my groceries off...       0  
8        Is there such a thing as dressing moderately, ...       0  
9        Is it just me or have you ever been in this ph...       0  
10                        What can you say about feminism?       0  
11                    How were the Calgary Flames founded?       0  
12       What is the dumbest, yet possibly true explana...       0  
13       Can we use our external hard disk as a OS as w...       0  
14       I am 30, living at home and have no boyfriend....       0  
15       What do you know about Bram Fischer and the Ri...       0  
16       How difficult is it to find a good instructor ...       0  
17                   Have you licked the skin of a corpse?       0  
18       Do you think Amazon will adopt an in house app...       0  
19       How many baronies might exist within a county ...       0  
20       How I know whether a girl had done sex before ...       0  
21       How do I become a fast learner both in my prof...       0  
22       Has the United States become the largest dicta...       1  
23       What is the strangest phenomenon you know of, ...       0  
24            Should I leave my friends and find new ones?       0  
25       Can you make Amazon Alexa trigger events in th...       0  
26       Why haven't two democracies never ever went fo...       0  
27                         How can I top CBSE i

In [5]:
df.shape[0], df[df.target == 1].shape[0], df[df.target == 1].shape[0] / df.shape[0]

(1306122, 80810, 0.06187017751787352)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.question_text, df.target, test_size=0.2, random_state=42)

In [7]:
sum(y_train) / len(y_train)

0.06216306487625096

In [8]:
sum(y_test) / len(y_test)

0.06069863144798545

TODO: split more evenly

In [9]:
vectorizer = HashingVectorizer(n_features=2**15, norm=None, alternate_sign=False)
X_train_transformed = vectorizer.fit_transform(X_train)

In [10]:
print(X_train_transformed[1])

  (0, 3815)	1.0
  (0, 5362)	1.0
  (0, 10087)	1.0
  (0, 12071)	1.0
  (0, 13677)	1.0
  (0, 19963)	1.0
  (0, 24734)	1.0
  (0, 25803)	1.0
  (0, 30025)	1.0


In [11]:
X_train[1]

'Do you have an adopted dog, how would you encourage people to adopt and not shop?'

In [12]:
X_test_transformed = vectorizer.transform(X_test)

In [13]:
log_clf = LogisticRegression(random_state=42)
log_clf.fit(X_train_transformed, y_train)

y_pred = log_clf.predict(X_test_transformed)

In [14]:
precision_recall_fscore_support(y_test, y_pred)

(array([0.96463313, 0.6914535 ]),
 array([0.98731706, 0.4398335 ]),
 array([0.97584329, 0.53766094]),
 array([245369,  15856]))

In [15]:
from sklearn.metrics import precision_score, recall_score
precision_score(y_test, y_pred), recall_score(y_test, y_pred)

(0.6914534999008527, 0.4398335015136226)

In [16]:
accuracy_score(y_test, y_pred)

0.9540855584266437